package handler

const (
	CallbackBuy                      = "buy"
	CallbackSell                     = "sell"
	CallbackStart                    = "start"
	CallbackConnect                  = "connect"
	CallbackPayment                  = "payment"
	CallbackTrial                    = "trial"
	CallbackActivateTrial            = "activate_trial"
	CallbackReferral                 = "referral"
	CallbackTopup                    = "topup"
	CallbackTopupSelect              = "topup_select"
	CallbackTopupCancel              = "topup_cancel"
	CallbackDevices                  = "devices"
	CallbackDevicesReset             = "devices_reset"
	CallbackDevicesResetConfirm      = "devices_reset_confirm"
	CallbackDevicesDeleteDevice      = "devices_del"
	CallbackStatus                   = "status"
	CallbackBroadcastConfirm         = "bcast_confirm"
	CallbackBroadcastConfirmExpired  = "bcast_confirm_exp"
	CallbackBroadcastConfirmInactive = "bcast_confirm_inact"
	CallbackBroadcastConfirmAll      = "bcast_confirm_all"
	CallbackBroadcastTest            = "bcast_test"
	CallbackBroadcastCancel          = "bcast_cancel"

	CallbackAdminPanelMenu        = "ap_menu"
	CallbackAdminPanelStats       = "ap_stats"
	CallbackAdminPanelBcast       = "ap_bcast"
	CallbackAdminPanelSystem      = "ap_sys"
	CallbackAdminPanelSync        = "ap_sync"
	CallbackAdminPanelUsers       = "ap_users"
	CallbackAdminUserTopup        = "ap_user_topup"
	CallbackAdminUserExtend       = "ap_user_extend"
	CallbackAdminUserEnable       = "ap_user_enable"
	CallbackAdminUserDisable      = "ap_user_disable"
	CallbackAdminUserResetDevices = "ap_user_reset_dev"
	CallbackAdminUserResetTraffic = "ap_user_reset_traffic"
)
